name: Continous integration for Tomatenquark
on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-go@v2-beta
        with:
          go-version: '^1.13.1'
      - name: Build for OSX
        run: go build -o libassetbundler.dylib -buildmode=c-shared github.com/tomatenquark/assetbundler/pkg/assetbundler
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-go@v2-beta
        with:
          go-version: '^1.13.1'
      - name: Build for Windows
        run:  go build -o libassetbundler.dylib -buildmode=c-shared github.com/tomatenquark/assetbundler/pkg/assetbundler
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2-beta
        with:
          go-version: '^1.13.1'
      - name: Build for Ubuntu
        run: go build -o libassetbundler.dylib -buildmode=c-shared github.com/tomatenquark/assetbundler/pkg/assetbundler
